[build]
  publish = "src"
  command = "npm install && npm run build"  # Add proper build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "src/functions"  # Ensure Netlify detects serverless functions